### ISSUE TITLE
is_utf8 helper

### ISSUE THREAD

**Issue by hadley** [krlmlr/enc#1]
We need some helper function that checks if a character vector is all utf-8.  

Not sure how to distinguish this from a class based test for utf8.

**Comment by krlmlr** [comment]
This will need C code to distinguish between "unknown" encoding and truly "all ASCII", basically an enhanced [do_encoding()](https://github.com/wch/r-source/blob/f22c596d8989413ea3977684e54304c43246e419/src/main/util.c#L1110-L1130) that also checks [IS_ASCII()](https://github.com/wch/r-source/blob/f22c596d8989413ea3977684e54304c43246e419/src/include/Defn.h#L123). Eventually this could be added upstream.

**Comment by hadley** [comment]
What's the difference between unknown and ascii? I thought unknown implied ascii.

**Comment by krlmlr** [comment]
Need to double-check.

**Comment by krlmlr** [comment]
There' a dedicated ASCII bit that is [set](https://github.com/wch/r-source/blob/f22c596d8989413ea3977684e54304c43246e419/src/main/envir.c#L3893) if the code of all characters is [127 or less](https://github.com/wch/r-source/blob/f22c596d8989413ea3977684e54304c43246e419/src/main/envir.c#L3830).

**Comment by hadley** [comment]
But that never gets used in `Encoding()`: https://github.com/wch/r-source/blob/2f2e4711ad7089f97f22c6b1ae25ba582d2e99a6/src/main/util.c#L1110

**Comment by hadley** [comment]
Also, none of the internal string representation stuff is in the exported API, so I think that means doing checks in R with `Encoding()` will be the easiest way forward.

**Comment by krlmlr** [comment]
ASCII implies unknown, but not the other way round. It will be difficult to detect pure ASCII strings using Encoding() only.

**Comment by hadley** [comment]
Yes, but it'll be accurate >95% of the time, I'd imagine
