### ISSUE TITLE
Rename to enc

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/enc#17]
because we do support other things than UTF-8.

CC @lorenzwalthert.

**Comment by lorenzwalthert** [comment]
Package renaming?

**Comment by krlmlr** [comment]
Yes. This needs to be synced with styler, I guess.

**Comment by lorenzwalthert** [comment]
Ok, will adapt the DESCRIPTION file and masked function calls. I think that's all it needs, right?

**Comment by lorenzwalthert** [comment]
I wonder how long the redirect from from krlmlr/utf8 to krlmlr/enc will continue to work.

**Comment by krlmlr** [comment]
Redirection seems surprisingly stable, but it would break if I created a repo named "utf8".

**Comment by lorenzwalthert** [comment]
So I guess you still need to update your DESCRIPTION, because it says: There is no package `enc`. Please let me know when we you do that so I can make the required changes in `styler` shortly after (or you change it all together) such that people who install it don't encounter errors.

**Comment by krlmlr** [comment]
Now would be a great time to change the import in styler ;-)
