### ISSUE TITLE
Consider using `LEVELS` instead of accessing sxpinfo directly

### ISSUE THREAD

**Issue by steve-s** [krlmlr/enc#23]
The following code from `encoding.c` could use `LEVELS` macro.
```
# define IS_BYTES(x) ((x)->sxpinfo.gp & BYTES_MASK)
# define IS_LATIN1(x) ((x)->sxpinfo.gp & LATIN1_MASK)
# define IS_ASCII(x) ((x)->sxpinfo.gp & ASCII_MASK)
# define IS_UTF8(x) ((x)->sxpinfo.gp & UTF8_MASK)
# define ENC_KNOWN(x) ((x)->sxpinfo.gp & (LATIN1_MASK | UTF8_MASK))
```
I believe that this is the right way of achieving this, since it works even if you do not define `USE_RINTERNALS` (but if you do, it compiles to the same machine code as before) and the "[R Internals](https://cran.r-project.org/doc/manuals/r-patched/R-ints.pdf)" document, the only documentation I could find for `LEVELS`, IMO clearly states that this is the contract of `LEVELS`:

> The bits can be accessed and set by the LEVELS and SETLEVELS macros, which names appear
to date back to the internal factor and ordered types and are now used in only a few places in
the code. The gp field is serialized/unserialized for the SEXPTYPEs other than NILSXP, SYMSXP
and ENVSXP.

Moreover, even `data.table` [uses this macro for the same purpose](https://github.com/Rdatatable/data.table/blob/master/src/chmatch.c#L3).

**Comment by krlmlr** [comment]
Thanks for raising this!
