### ISSUE TITLE
utf8 should give advice on testing for encoding problems

### ISSUE THREAD

**Issue by hadley** [krlmlr/enc#3]
i.e. how do you create an encoding problem that fails reliably on all platforms.

I think it's something like:
- make sure you have "Encoding: UTF-8" in your DESCRIPTION (otherwise, use unicode escapes instead of literal characters)
- use `iconv` to convert to latin-1 encoding. Maybe utf-8 should have a helper method for this case?

Maybe we should also provide testthat helper, `expect_utf8()` ?

**Comment by hadley** [comment]
``` R
latin1 <- function(x) {
  iconv(x, Encoding(x), "latin1")
}
latin1("à")
```

**Comment by krlmlr** [comment]
Partly done in a63dacc0946a, see `to_alien()`.

**Comment by krlmlr** [comment]
We now have `rlang::mut_latin1_locale()` etc.. utf8 implements deep recoding and reading/writing, rlang works on strings and vectors only.
