### ISSUE TITLE
README needs to give more advice

### ISSUE THREAD

**Issue by hadley** [krlmlr/enc#6]
- encoding is property of individual string, not entire vector
- always use utf-8 encoding because ...
- prefer packages that return utf-8 encoded values
- prefer stringi/stringr over base functions
- mention particularly problematic base functions (paste? gsub?)

**Comment by krlmlr** [comment]
Starting to extend the README now. What's problematic about `paste()` and `gsub()`? A quick test seems to indicate that these functions treat encoding correctly, and return UTF-8 whenever at least one of the args is UTF-8 (on Windows).

**Comment by hadley** [comment]
I don't remember 😢 Maybe they were problematic in earlier versions of R?
